"""Rename userresource to resource

Revision ID: 2d8b71248ae4
Revises: 02e08e9dd209
Create Date: 2018-10-13 13:09:04.296041

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlalchemy_utils as sau

# revision identifiers, used by Alembic.
revision = '2d8b71248ae4'
down_revision = '02e08e9dd209'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
    sa.Column('created_at', sau.ArrowType(), nullable=False),
    sa.Column('updated_at', sau.ArrowType(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(8), nullable=True),
    sa.Column('quantity_available', sa.BigInteger(), nullable=True),
    sa.Column('quantity_needed', sa.BigInteger(), nullable=True),
    sa.Column('fulfilled', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_created_at'), 'resources', ['created_at'], unique=False)
    op.create_index(op.f('ix_resources_type'), 'resources', ['type'], unique=False)
    op.create_index(op.f('ix_resources_updated_at'), 'resources', ['updated_at'], unique=False)
    op.drop_constraint('user_resource_fulfillment_ibfk_2', 'user_resource_fulfillment', type_='foreignkey')
    op.drop_constraint('user_resource_fulfillment_ibfk_1', 'user_resource_fulfillment', type_='foreignkey')
    op.drop_table('user_resources')
    op.create_foreign_key('fk_urf_resources_fulfilling', 'user_resource_fulfillment', 'resources', ['fulfilling_resource_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key('fk_urf_resources_fulfilled', 'user_resource_fulfillment', 'resources', ['fulfilled_resource_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_urf_resources_fulfilled', 'user_resource_fulfillment', type_='foreignkey')
    op.drop_constraint('fk_urf_resources_fulfilling', 'user_resource_fulfillment', type_='foreignkey')
    op.create_foreign_key('user_resource_fulfillment_ibfk_1', 'user_resource_fulfillment', 'user_resources', ['fulfilled_resource_id'], ['id'], onupdate='CASCADE')
    op.create_foreign_key('user_resource_fulfillment_ibfk_2', 'user_resource_fulfillment', 'user_resources', ['fulfilling_resource_id'], ['id'], onupdate='CASCADE')
    op.create_table('user_resources',
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('user_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('type', mysql.VARCHAR(length=8), nullable=True),
    sa.Column('quantity_available', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('quantity_needed', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('fulfilled', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('category_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='fk_user_resources_categories', onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_resources_ibfk_2', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_resources_updated_at'), table_name='resources')
    op.drop_index(op.f('ix_resources_type'), table_name='resources')
    op.drop_index(op.f('ix_resources_created_at'), table_name='resources')
    op.drop_table('resources')
    # ### end Alembic commands ###
