"""association field to user table

Revision ID: 4b6683de8e6f
Revises: bdbda1f6de37
Create Date: 2018-10-13 20:17:13.000973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b6683de8e6f'
down_revision = 'bdbda1f6de37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('association', sa.Unicode(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'association')
    # ### end Alembic commands ###
