"""Linecon

Revision ID: 703ab7d5870f
Revises: 479aa1adc1c5
Create Date: 2018-10-14 00:37:19.089714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '703ab7d5870f'
down_revision = '479aa1adc1c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('linecon_icon', sa.UnicodeText(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'linecon_icon')
    # ### end Alembic commands ###
