"""resource description field

Revision ID: 9f19a334afb0
Revises: 7032046b3486
Create Date: 2018-10-13 23:12:14.114391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f19a334afb0'
down_revision = '7032046b3486'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('description', sa.UnicodeText(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resources', 'description')
    # ### end Alembic commands ###
