"""empty message

Revision ID: bdbda1f6de37
Revises: 9aeda8f60a9b
Create Date: 2018-10-13 16:31:33.558975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdbda1f6de37'
down_revision = '9aeda8f60a9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('name', sa.UnicodeText(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resources', 'name')
    # ### end Alembic commands ###
