"""empty message

Revision ID: c72922c6544f
Revises: 1d694454cc8b
Create Date: 2018-10-14 00:59:16.591902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c72922c6544f'
down_revision = '1d694454cc8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('requested', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resources', 'requested')
    # ### end Alembic commands ###
