"""resource categories

Revision ID: d0ff6064fcd8
Revises: 08b88db1317a
Create Date: 2018-10-13 22:42:18.292749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0ff6064fcd8'
down_revision = '08b88db1317a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('description', sa.UnicodeText(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resources', 'description')
    # ### end Alembic commands ###
