COUNTRY_CODES = (
    ("AF", "افغانستان"),
    ("AX", "Landskapet Åland"),
    ("AL", "Shqipëria"),
    ("DZ", "الجزائر"),
    ("AS", "Amerika Sāmoa"),
    ("AD", "Andorra"),
    ("AO", "Angola"),
    ("AI", "Anguilla"),
    ("AQ", "Antarctica"),
    ("AG", "Antigua & Barbuda"),
    ("AR", "Argentina"),
    ("AM", "Հայաստան"),
    ("AW", "Aruba"),
    ("AC", "Ascension Island"),
    ("AU", "Australia"),
    ("AT", "Österreic"),
    ("AZ", "Azərbaycan"),
    ("BS", "Bahamas"),
    ("BH", "البحرين"),
    ("BD", "বাংলাদেশ"),
    ("BB", "Barbados"),
    ("BY", "Беларусь"),
    ("BE", "België"),
    ("BZ", "Belize"),
    ("BJ", "Bénin"),
    ("BM", "Bermuda"),
    ("BT", "འབྲུག་ཡུལ"),
    ("BO", "Bolivia"),
    ("BA", "Босна и Херцеговина"),
    ("BW", "Botswana"),
    ("BR", "Brasil"),
    ("IO", "British Indian Ocean Territory"),
    ("VG", "British Virgin Islands"),
    ("BN", "بروني"),
    ("BG", "България"),
    ("BF", "Burkina Faso"),
    ("BI", "Uburundi"),
    ("KH", "កម្ពុជា"),
    ("CM", "Cameroun"),
    ("CA", "Canada"),
    ("IC", "Canary Islands"),
    ("CV", "Cabo Verde	"),
    ("BQ", "Caribbean Netherlands"),
    ("KY", "Cayman Islands"),
    ("CF", "Ködörösêse tî Bêafrîka"),
    ("EA", "Ceuta & Melilla"),
    ("TD", "جمهورية تشاد"),
    ("CL", "Chile"),
    ("CN", "中国"),
    ("CX", "Christmas Island"),
    ("CC", "Cocos (Keeling) Islands"),
    ("CO", "Colombia"),
    ("KM", "الاتحاد القمري"),
    ("CG", "République du Congo"),
    ("CD", "République démocratique du Congo"),
    ("CK", "Cook Islands"),
    ("CR", "Costa Rica"),
    ("CI", "Côte d’Ivoire"),
    ("HR", "Hrvatska"),
    ("CU", "Cuba"),
    ("CW", "Curaçao"),
    ("CY", "Κύπρος"),
    ("CZ", "Česká republika"),
    ("DK", "Denmark"),
    ("DG", "Diego Garcia"),
    ("DJ", "جيبوتي"),
    ("DM", "Dominica"),
    ("DO", "República Dominicana"),
    ("EC", "Ecuador"),
    ("EG", "مصر"),
    ("SV", "El Salvador"),
    ("GQ", "Equatorial Guinea"),
    ("ER", "إرتريا"),
    ("EE", "Eesti"),
    ("ET", "ኢትዮጵያ"),
    ("EZ", "Eurozone"),
    ("FK", "Falkland Islands"),
    ("FO", "Føroyar"),
    ("FJ", "Viti"),
    ("FI", "Suomi"),
    ("FR", "France"),
    ("GF", "Guyane"),
    ("PF", "Polynésie française"),
    ("TF", "French Southern Territories"),
    ("GA", "République gabonaise"),
    ("GM", "Gambia"),
    ("GE", "საქართველო"),
    ("DE", "Deutschland"),
    ("GH", "Gaana"),
    ("GI", "Gibraltar"),
    ("GR", "Ελλάς"),
    ("GL", "Kalaallit Nunaat"),
    ("GD", "Grenada"),
    ("GP", "Guadeloupe"),
    ("GU", "Guåhån"),
    ("GT", "Guatemala"),
    ("GG", "Guernsey"),
    ("GN", "Guinée"),
    ("GW", "Guiné-Bissau"),
    ("GY", "Guyana"),
    ("HT", "Haïti"),
    ("HN", "Honduras"),
    ("HK", "香港"),
    ("HU", "Magyarország"),
    ("IS", "Ísland"),
    ("IN", "Bhārat"),
    ("ID", "Indonesia"),
    ("IR", "ایران"),
    ("IQ", "العراق"),
    ("IE", "Éire"),
    ("IM", "Ellan Vannin"),
    ("IL", "ישראל"),
    ("IT", "Italia"),
    ("JM", "Jamaica"),
    ("JP", "日本"),
    ("JE", "Jersey"),
    ("JO", "الأردن"),
    ("KZ", "Qazaqstan"),
    ("KE", "Kenya"),
    ("KI", "Ribaberiki Kiribati"),
    ("XK", "Kosovës"),
    ("KW", "دولة الكويت"),
    ("KG", "Кыргызстан"),
    ("LA", "ະເທດລາວ"),
    ("LV", "Latvija"),
    ("LB", "لبنان"),
    ("LS", "Lesotho"),
    ("LR", "Liberia"),
    ("LY", "ليبيا"),
    ("LI", "Liechtenstein"),
    ("LT", "Lietuva"),
    ("LU", "Lëtzebuerg"),
    ("MO", "澳門"),
    ("MK", "Македонија"),
    ("MG", "Madagasikara"),
    ("MW", "Malaŵi"),
    ("MY", "مليسيا"),
    ("MV", "Dhivehi Raajje"),
    ("ML", "Mali"),
    ("MT", "Malta"),
    ("MH", "Aorōkin M̧ajeļ"),
    ("MQ", "Martinique"),
    ("MR", "موريتانيا"),
    ("MU", "Maurice"),
    ("YT", "Mayotte"),
    ("MX", "México"),
    ("FM", "Micronesia"),
    ("MD", "Moldova"),
    ("MC", "Múnegu"),
    ("MN", "Монгол Улс"),
    ("ME", "Црна Гора"),
    ("MS", "Montserrat"),
    ("MA", "المغرب"),
    ("MZ", "Moçambique"),
    ("MM", "မြန်မာ"),
    ("NA", "Namibia"),
    ("NR", "Naoero"),
    ("NP", "Nepāl"),
    ("NL", "Nederland"),
    ("NC", "Nouvelle-Calédonie"),
    ("NZ", "Aotearoa"),
    ("NI", "Nicaragua"),
    ("NE", "Nijeriya"),
    ("NG", "Nigeria"),
    ("NU", "Niuē"),
    ("NF", "Norf'k Ailen"),
    ("KP", "조선민주주의인민공화국"),
    ("MP", "Notte Mariånass"),
    ("NO", "Norge"),
    ("OM", "عُمان"),
    ("PK", "پاکستان‬"),
    ("PW", "Belau"),
    ("PS", "فلسطين‎"),
    ("PA", "Panamá"),
    ("PG", "Papua Niugini"),
    ("PY", "Paraguay"),
    ("PE", "Perú"),
    ("PH", "Pilipinas"),
    ("PN", "Pitkern Ailen"),
    ("PL", "Polska"),
    ("PT", "Portugal"),
    ("PR", "Puerto Rico"),
    ("QA", "قطر"),
    ("RE", "Réunion"),
    ("RO", "România"),
    ("RU", "Россия"),
    ("RW", "Rwanda"),
    ("WS", "Sāmoa"),
    ("SM", "San Marino"),
    ("ST", "São Tomé & Príncipe"),
    ("SA", "المملكة العربية السعودية"),
    ("SN", "Sénégal"),
    ("RS", "Србија"),
    ("SC", "Sesel"),
    ("SL", "Sierra Leone"),
    ("SG", "新加坡"),
    ("SX", "Sint Maarten"),
    ("SK", "Slovensko"),
    ("SI", "Slovenija"),
    ("SB", "Solomon Aelan"),
    ("SO", "الصومال"),
    ("ZA", "Suid-Afrika"),
    ("GS", "South Georgia & South Sandwich Islands"),
    ("KR", "대한민국/大韓民國"),
    ("SS", "Sudan Kusini"),
    ("ES", "España"),
    ("LK", "ශ්‍රී ලංකා"),
    ("BL", "Saint-Barthélemy"),
    ("SH", "St. Helena"),
    ("KN", "St. Kitts & Nevis"),
    ("LC", "St. Lucia"),
    ("MF", "St. Martin"),
    ("PM", "Saint-Pierre et Miquelon"),
    ("VC", "St. Vincent & Grenadines"),
    ("SD", "السودان"),
    ("SR", "Suriname"),
    ("SJ", "Svalbard & Jan Mayen"),
    ("SZ", "eSwatini"),
    ("SE", "Sweden"),
    ("CH", "Sverige	"),
    ("SY", "سورية"),
    ("TW", "中華民國"),
    ("TJ", "Тоҷикистон"),
    ("TZ", "Tanzania"),
    ("TH", "ราชอาณาจักรไทย"),
    ("TL", "Timor Lorosa'e"),
    ("TG", "Togo"),
    ("TK", "Tokelau"),
    ("TO", "Tonga"),
    ("TT", "Trinidad & Tobago"),
    ("TA", "Tristan da Cunha"),
    ("TN", "تونس"),
    ("TR", "Türkiye"),
    ("TM", "Türkmenistan"),
    ("TC", "Turks & Caicos Islands"),
    ("TV", "Tuvalu"),
    ("UM", "U.S. Outlying Islands"),
    ("VI", "U.S. Virgin Islands"),
    ("UG", "Uganda"),
    ("UA", "Україна"),
    ("AE", "الإمارات العربيّة المتّحدة"),
    ("GB", "United Kingdom"),
    ("UN", "United Nations"),
    ("US", "United States"),
    ("UY", "Uruguay"),
    ("UZ", "Ўзбекистон"),
    ("VU", "Vanuatu"),
    ("VA", "Città del Vaticano"),
    ("VE", "Venezuela"),
    ("VN", "Việt Nam"),
    ("WF", "Wallis-et-Futuna"),
    ("EH", "Western Sahara"),
    ("YE", "اليمن"),
    ("ZM", "Zambia"),
    ("ZW", "Zimbabwe"),
)